# Generated by Django 5.2.4 on 2025-07-27 01:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(verbose_name='Süre (gün)')),
                ('profit_percent', models.PositiveIntegerField(default=100, verbose_name='Getiri Oranı (%)')),
                ('return_percentage', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_support_link', models.URLField(max_length=300, verbose_name='WhatsApp Destek Bağlantısı')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Beklenen Getiri')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('refunded', 'İade Edildi')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.package')),
            ],
            options={
                'verbose_name': 'Yatırım',
                'verbose_name_plural': 'Yatırımlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('admin_approved', models.BooleanField(default=False)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_confirmation', to='core.investment')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Kullanıcı'), ('admin', 'Admin')], default='user', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.profile'),
        ),
        migrations.CreateModel(
            name='UserInvestmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pending_payments', models.PositiveIntegerField(default=0)),
                ('has_active_investment', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_summary', to='core.profile')),
            ],
            options={
                'verbose_name': 'Yatırım Özeti',
                'verbose_name_plural': 'Yatırım Özetleri',
            },
        ),
    ]
