# Generated by Django 5.2.4 on 2025-07-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yatırım', 'verbose_name_plural': 'Yatırımlar'},
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='invested_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='package',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İptal Tarihi'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İade Tarihi'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('refunded', 'İade Edildi')], default='pending', max_length=20),
        ),
    ]
