# Generated by Django 5.2.4 on 2025-07-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='return_percentage',
        ),
    ]
