# Generated by Django 5.2.4 on 2025-07-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.AddField(
            model_name='investment',
            name='crypto_network',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kripto Ağ (Admin Girişi)'),
        ),
        migrations.AddField(
            model_name='investment',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kripto Cüzdan Adresi (Admin Girişi)'),
        ),
        migrations.AddField(
            model_name='package',
            name='crypto_network',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kripto Ağı'),
        ),
        migrations.AddField(
            model_name='package',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kripto Cüzdan Adresi'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
    ]
