# Generated by Django 5.2.4 on 2025-07-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_package_return_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kısa Açıklama'),
        ),
    ]
