# Generated by Django 5.2.4 on 2025-07-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_package_amount_remove_package_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Cüzdan ismi, örn: 'WafelInvest BTC Cüzdanı'", max_length=100)),
                ('address', models.CharField(max_length=255, verbose_name='Kripto Cüzdan Adresi')),
                ('network', models.CharField(max_length=100, verbose_name='Kripto Ağ')),
                ('active', models.BooleanField(default=True, help_text='Aktif olan cüzdan kullanıcıya gösterilir')),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='crypto_network',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='crypto_wallet_address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='crypto_network',
        ),
        migrations.RemoveField(
            model_name='package',
            name='crypto_wallet_address',
        ),
    ]
