# Generated by Django 5.2.4 on 2025-07-16 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvestmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Soyad')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Yatırılan Tutar (€)')),
                ('total_return', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Getiri (€)')),
                ('pending_payments', models.PositiveIntegerField(default=0, verbose_name='Onay Bekleyen Ödeme Sayısı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yatırım Özeti',
                'verbose_name_plural': 'Yatırım Özetleri',
            },
        ),
    ]
