# Generated by Django 5.2.4 on 2025-07-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userinvestmentsummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentconfirmation',
            options={'verbose_name': 'Ödeme Onayı', 'verbose_name_plural': 'Ödeme Onayları'},
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='currency',
            field=models.CharField(default=100, help_text='Örn: BTC, ETH', max_length=10, verbose_name='Kripto Para Birimi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='expected_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Paket Açıklaması'),
        ),
        migrations.AddField(
            model_name='package',
            name='expected_return_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Yüzde olarak beklenen getiri', max_digits=5),
        ),
        migrations.AddField(
            model_name='package',
            name='refundable',
            field=models.BooleanField(default=True, verbose_name='İade Edilebilir mi?'),
        ),
        migrations.AddField(
            model_name='package',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Sitede Gösterilsin mi?'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement',
            field=models.TextField(blank=True, null=True, verbose_name='Anasayfa Duyurusu'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='WafelInvest', max_length=100, verbose_name='Site Adı'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Destek E-Postası'),
        ),
        migrations.AddField(
            model_name='userinvestmentsummary',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme'),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='admin_approved',
            field=models.BooleanField(default=False, verbose_name='Admin Onayı'),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='payment_screenshot',
            field=models.ImageField(upload_to='payment_screenshots/', verbose_name='Ödeme Ekran Görüntüsü'),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='whatsapp_number',
            field=models.CharField(max_length=20, verbose_name='WhatsApp Numarası'),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Toplam Yatırılan Tutar (€)'),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Toplam Getiri (€)'),
        ),
    ]
