# Generated by Django 5.2.4 on 2025-07-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chatmessage_options_remove_chatmessage_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
