# Generated by Django 5.2.4 on 2025-07-30 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.RemoveField(
            model_name='paymentconfirmation',
            name='whatsapp_number',
        ),
    ]
