# Generated by Django 5.2.4 on 2025-07-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paymentconfirmation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentconfirmation',
            options={},
        ),
        migrations.RemoveField(
            model_name='cryptowallet',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='expected_return_percentage',
        ),
        migrations.RemoveField(
            model_name='package',
            name='refundable',
        ),
        migrations.RemoveField(
            model_name='package',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='support_email',
        ),
        migrations.RemoveField(
            model_name='userinvestmentsummary',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='investment',
            name='expected_return',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Beklenen Getiri'),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='payment_screenshot',
            field=models.ImageField(upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='whatsapp_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Yatırılan Tutar (€)'),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Getiri (€)'),
        ),
    ]
