# Generated by Django 5.2.4 on 2025-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_paymentconfirmation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='profit_percent',
            field=models.PositiveIntegerField(default=100, verbose_name='Getiri Oranı (%)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='expected_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Beklenen Getiri'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(verbose_name='Süre (gün)'),
        ),
    ]
