# Generated by Django 5.2.4 on 2025-07-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_package_profit_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestmentsummary',
            name='has_active_investment',
            field=models.BooleanField(default=False, verbose_name='Aktif Yatırımı Var mı?'),
        ),
    ]
