# Generated by Django 5.2.4 on 2025-07-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userinvestmentsummary_has_active_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Toplam Yatırılan Tutar (€)'),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_return',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Toplam Getiri (€)'),
        ),
    ]
