# Generated by Django 5.2.4 on 2025-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userinvestmentsummary_total_invested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestmentsummary',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userinvestmentsummary',
            name='phone',
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='whatsapp_number',
            field=models.CharField(max_length=20, verbose_name='WhatsApp Numarası'),
        ),
    ]
