# Generated by Django 5.2.4 on 2025-07-20 20:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_userinvestmentsummary_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Toplam Yatırılan Tutar (€)'),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_return',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Toplam Getiri (€)'),
        ),
    ]
