# Generated by Django 5.2.4 on 2025-07-20 21:22

import core.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0013_alter_userinvestmentsummary_total_invested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Kullanıcı',
                'verbose_name_plural': 'Admin Kullanıcılar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', models.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', models.Manager()),
            ],
        ),
    ]
