# Generated by Django 5.2.4 on 2025-07-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_adminuser_regularuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Adminler'},
        ),
    ]
