# Generated by Django 5.2.4 on 2025-07-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_adminuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin Kullanıcı', 'verbose_name_plural': 'Admin Kullanıcılar'},
        ),
    ]
