# Generated by Django 5.2.4 on 2025-07-21 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_adminuser_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinvestmentsummary',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='profile',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinvestmentsummary',
            name='profile',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='investment_summary', to='core.profile'),
            preserve_default=False,
        ),
    ]
