# Generated by Django 5.2.4 on 2025-07-21 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userinvestmentsummary_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestmentsummary',
            name='owner',
        ),
    ]
