# Generated by Django 5.2.4 on 2025-07-21 10:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_userinvestmentsummary_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptowallet',
            name='network',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='whatsapp_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='has_active_investment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='pending_payments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='userinvestmentsummary',
            name='total_return',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
