# Generated by Django 5.2.4 on 2025-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_cryptowallet_active_alter_cryptowallet_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='RegularUser',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Kullanıcı'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
