# Generated by Django 5.2.4 on 2025-07-23 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_faq_testimonial_package_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
    ]
