# Generated by Django 5.2.4 on 2025-07-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_faq_delete_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
