# Generated by Django 5.2.4 on 2025-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_package_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(verbose_name='Süre (gün)'),
        ),
    ]
