# Generated by Django 5.2.4 on 2025-07-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_package_duration_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptowallet',
            options={'ordering': ['-id']},
        ),
    ]
