# Generated by Django 5.2.4 on 2025-07-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_cryptowallet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='return_percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
